version: '3.9'

services:

  quarkus-lab:
    image: quarkus-lab
    container_name: quarkus-lab
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost/health || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - 8080:8080
    environment:
      - QUARKUS_HTTP_HOST=0.0.0.0
      - QUARKUS_HTTP_port=8080
    build: .
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/workspace
      - ~/.m2:/root/.m2