version: '3.9'

services:

  quarkus-lab:
    image: quarkus-lab
    container_name: quarkus-lab
    command : ["sh", "-c", "tail -f /dev/null"]
    ports:
      - 8080:8080
    environment:
      - QUARKUS_HTTP_HOST=0.0.0.0
      - QUARKUS_HTTP_port=8080
    build: .
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/workspace
      - ~/.m2:/root/.m2